# Generated by Django 4.1.7 on 2023-03-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='costohistoricomedicamento',
            name='idmedicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.medicamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idCargoEmpleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.cargoempleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idEspecialidadMedico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.especialidadmedico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idTipoDocumentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipodocumentos'),
        ),
        migrations.AlterField(
            model_name='impuestohitorico',
            name='idImpuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='idImpuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.proveedor'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='idTipoMuestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipomuestra'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idTipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipodocumentos'),
        ),
        migrations.AlterField(
            model_name='preciohistoricomedicamento',
            name='idmedicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.medicamento'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='idsubtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.subtipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idEmpleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.empleado'),
        ),
    ]
