# Generated by Django 4.1.7 on 2023-04-14 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='idImpuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sesion',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='idImpuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.impuesto'),
        ),
    ]
