# Generated by Django 4.1.7 on 2023-03-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
