# Generated by Django 4.1.7 on 2023-03-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('metodoConservacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('idSubtipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.subtipo')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaNacimiento', models.DateTimeField()),
                ('documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipodocumentos')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
                ('idTipoMuestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipomuestra')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActual', models.DateTimeField(auto_now_add=True)),
                ('fechaProgramada', models.DateTimeField()),
                ('fechaMaxima', models.DateTimeField()),
                ('activa', models.PositiveSmallIntegerField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
    ]
