# Generated by Django 4.1.7 on 2023-03-31 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioHistoricoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fechaProgramada', models.DateTimeField()),
                ('observacion', models.CharField(max_length=100)),
                ('idLaboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.laboratorios')),
                ('idMuestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.muestra')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
    ]
