# Generated by Django 4.1.7 on 2023-04-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivos', models.CharField(max_length=50)),
                ('confirmacion', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
