# Generated by Django 4.1.7 on 2023-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intentos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
