# Generated by Django 4.1.7 on 2023-03-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_cita_idpaciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaActual',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='costohistoricomedicamento',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='impuestohitorico',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fechaRegistro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='preciohistoricomedicamento',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateTimeField(),
        ),
    ]
