# Generated by Django 4.1.7 on 2023-04-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_tipo_idimpuesto_usuario_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudo',
            name='fechaFacturacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
