# Generated by Django 4.1.7 on 2023-04-01 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_autorizacionpaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('idAutorizacionPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.autorizacionpaciente')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.empleado')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
    ]
