# Generated by Django 4.1.7 on 2023-03-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_parametrosgenerales_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='diasTratamiento',
            field=models.PositiveIntegerField(default='15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='estado',
            field=models.CharField(default='Sin información', max_length=50),
            preserve_default=False,
        ),
    ]
