# Generated by Django 4.1.7 on 2023-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_enfermedad_sintoma_enfermedaddetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedaddetalle',
            name='activo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
