# Generated by Django 4.1.7 on 2023-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_recaudo_fechafacturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudo',
            name='activa',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
