# Generated by Django 4.1.7 on 2023-04-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_recaudo_activa_recaudo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudo',
            name='idConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.consulta'),
        ),
    ]
