# Generated by Django 4.1.7 on 2023-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_enfermedaddetalle_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedaddetalle',
            name='activo',
        ),
        migrations.AddField(
            model_name='enfermedaddetalle',
            name='delete',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfermedaddetalle',
            name='update',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
