# Generated by Django 4.1.7 on 2023-04-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='idCita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.empleado'),
        ),
    ]
