# Generated by Django 4.1.7 on 2023-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_remove_enfermedaddetalle_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedaddetalle',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='enfermedaddetalle',
            name='update',
        ),
    ]
