# Generated by Django 4.1.7 on 2023-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_recaudo_idconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudo',
            name='fechaFacturacion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
