# Generated by Django 4.1.7 on 2023-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_alter_recaudo_fechafacturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudo',
            name='noFactura',
            field=models.CharField(max_length=50),
        ),
    ]
