# Generated by Django 4.1.7 on 2023-04-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_alter_recaudo_nofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recaudodetallemedicamento',
            name='descuento',
        ),
    ]
