# Generated by Django 4.1.7 on 2023-04-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_remove_recaudodetallemedicamento_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlativosar',
            name='activo',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
