# Generated by Django 4.1.7 on 2023-03-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idCita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipomuestra')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
    ]
