# Generated by Django 4.1.7 on 2023-03-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0009_parametrosgenerales_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDiagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.diagnostico')),
                ('idEnfermedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEnfermedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.enfermedad')),
                ('idMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.medicamento')),
                ('idSintoma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.sintoma')),
            ],
        ),
    ]
