# Generated by Django 4.1.7 on 2023-03-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0010_diagnosticodetalle_consultadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tipo')),
            ],
        ),
    ]
