# Generated by Django 4.1.7 on 2023-03-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0011_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=100)),
                ('idTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.paciente')),
            ],
        ),
    ]
