# Generated by Django 4.1.7 on 2023-03-30 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0012_resultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='idTratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.tratamiento'),
        ),
    ]
