# Generated by Django 4.1.7 on 2023-03-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0013_alter_resultados_idtratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
